# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-27 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatter',
            name='name',
        ),
    ]
